# Generated by Django 6.0.2 on 2026-03-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_employee_medicine_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
